"""
Local Development Server for Property API

This creates a FastAPI server that wraps the existing Lambda function,
allowing you to test the API locally with real HTTP requests.

Usage:
    pip install fastapi uvicorn
    python local_server.py

Then access:
    http://localhost:8000/properties
    http://localhost:8000/properties/{id}
    http://localhost:8000/properties/stats
"""
print("STARTING SCRIPT")

from fastapi import FastAPI, Request
print("FASTAPI IMPORTED")

from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
print("UVICORN IMPORTED")

import json

# Import the Lambda handler
from lambda_function import lambda_handler
print("LAMBDA IMPORTED")

# Create FastAPI app
app = FastAPI(
    title="Foreclosed Property API",
    description="Local development server for testing the Property API",
    version="1.0.0"
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


async def handle_request(request: Request):
    """
    Convert FastAPI request to Lambda event format and call the Lambda handler
    """
    # Extract path parameters if any
    path_params = dict(request.path_params) if request.path_params else None
    
    # Extract query parameters
    query_params = dict(request.query_params) if request.query_params else None
    
    # Create Lambda event
    event = {
        "httpMethod": request.method,
        "path": request.url.path,
        "headers": dict(request.headers),
        "queryStringParameters": query_params,
        "pathParameters": path_params,
        "body": None,
        "isBase64Encoded": False
    }
    
    # Call the Lambda handler
    lambda_response = lambda_handler(event, None)
    
    # Convert Lambda response to FastAPI response
    return JSONResponse(
        content=json.loads(lambda_response["body"]),
        status_code=lambda_response["statusCode"],
        headers=lambda_response.get("headers", {})
    )


# Route all requests to the handler
@app.api_route("/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"])
async def catch_all(request: Request, path: str):
    """Catch all routes and forward to Lambda handler"""
    return await handle_request(request)


@app.get("/")
async def root(request: Request):
    """Root endpoint - API information"""
    return await handle_request(request)


if __name__ == "__main__":
    print("=" * 60)
    print("🚀 Starting Foreclosed Property API Local Server")
    print("=" * 60)
    print()
    print("📍 Server will be available at:")
    print("   http://localhost:8000")
    print()
    print("📚 API Documentation (auto-generated by FastAPI):")
    print("   http://localhost:8000/docs")
    print()
    print("🔗 Example Endpoints:")
    print("   http://localhost:8000/properties")
    print("   http://localhost:8000/properties?city=ROXAS&limit=10")
    print("   http://localhost:8000/properties?min_price=500000&max_price=1000000")
    print("   http://localhost:8000/properties/pagibig_858202309280002")
    print("   http://localhost:8000/properties/stats")
    print()
    print("💡 Press Ctrl+C to stop the server")
    print("=" * 60)
    print()
    
    # Run the server
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info"
    )

# Made with Bob
