name: Loader to Lambda Function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/loader/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create build directory
        run: |
          mkdir -p build
          pip install -r backend/loader/requirements.txt -t build
          cp backend/loader/*.py build
          cd build && zip -r ../infra/loader_lambda.zip .

      - name: Create dummy ZIP files for missing lambdas
        working-directory: infra  
        run: |
          # Create minimal dummy zip files for validation
          echo "dummy" | zip -q api_lambda.zip -
          echo "dummy" | zip -q scraper_lambda.zip -

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -target=aws_lambda_function.loader_lambda -no-color

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -target=aws_lambda_function.loader_lambda -auto-approve
